name: Minimal Workflow Test

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Minimal workflow is running successfully!"
